version: "3"

services:

  zuad:
    container_name: zuad
    image: zuanet/zuad:latest
    restart: unless-stopped
    ports:
      - "46005:46005/tcp"
      - "46009:46009/tcp"
    volumes:
      - $HOME/.zuad:/app/data/
# use managed volumes
#      - zuad:/app/data/
    command:  ./zuad --utxoindex --connect=mainnet-dnsseed-1.zuanetwork.com --appdir=/app/data
